sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licences:
    - 'android-sdk-license-.+'
script: ./gradlew clean build test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_022658120507_key -iv $encrypted_022658120507_iv -in dist/googleplay-developer-key.json.enc -out dist/googleplay-developer-key.json -d
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew publish
  on:
    tags: true
