sudo: false
language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licences:
    - 'android-sdk-license-.+'
script: ./gradlew --info build
