sudo: false
language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licences:
    - 'android-sdk-license-.+'
env:
before_install:
  - openssl aes-256-cbc -K $encrypted_022658120507_key -iv $encrypted_022658120507_iv -in dist/googleplay-developer-key.json.enc -out dist/googleplay-developer-key.json -d
script:
  - ./gradlew clean assemble test publish
